Mal/standardtekstar.json
Lagt til standardtekster for app-sider.
=> Oppdatert standardtekster for app

Testreglar/134/App/app-1.3.4a.json
@ABJORS litt usikker på utfall, så gjerne dobbeltsjekk om utfall er riktig.
=> Fikser #130 app-1.3.4a mangler steg for å sjekke om innhold kan brukes

Testreglar/252/Nett/nett-2.5.2a.json
Dette er ment gjennomlesning og ikke vanlig kvalitetssikring, fordi vi er litt usikker på punkt to i kravet om mekanisme for å avbryte eller angre hvis funksjonen utføres på slipphandlingen. Kan gjerne ha et møte etter gjennomlesning.
=> nett-2.5.2a er klar for KS

package-lock.json, package.json
- typescript-eslint/eslint-plugin: 6.1.0
- typescript-eslint/parser: 6.1.0
- eslint 8.45.0
=> Depend:  Bump eslint til siste versjon

Testreglar/1.4.1/App/app-1.4.1a.json, Testreglar/1.4.1/App/app-1.4.1b.json, Testreglar/1.4.1/App/app-1.4.1c.json, Testreglar/1.4.1/Nett/nett-1.4.1a.json, Testreglar/1.4.1/Nett/nett-1.4.1b.json, Testreglar/1.4.1/Nett/nett-1.4.1c.json, Testreglar/1.4.10/App/app-1.4.10a.json, Testreglar/1.4.10/Nett/nett-1.4.10a.json, Testreglar/1.4.11/App/app-1.4.11a.json, Testreglar/1.4.11/App/app-1.4.11b.json, Testreglar/1.4.11/App/app-1.4.11c.json, Testreglar/1.4.11/Nett/nett-1.4.11a.json, Testreglar/1.4.11/Nett/nett-1.4.11b.json, Testreglar/1.4.11/Nett/nett-1.4.11c.json, Testreglar/1.4.2/Nett/1.4.2a.json, Testreglar/1.4.3/App/app-143a.json, Testreglar/1.4.3/Nett/1.4.3a.json, Testreglar/1.4.3/Nett/1.4.3b.json, Testreglar/1.4.3/Nett/1.4.3c.json, Testreglar/1.4.4/Nett/1.4.4a.json, Testreglar/1.4.5/Nett/1.4.5a.json, Utdatert/1.3.5/App/app-android-1.3.5a.json, Utdatert/1.3.5/App/app-ios-1-3-5a.json, Utdatert/1.4.1/1.4.1a.json, Utdatert/1.4.1/1.4.1b.json, Utdatert/1.4.1/1.4.1c.json
- [Oppdatert format 1.4.1](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/d78a2a3c08482ed0b4664df8ed387a408126e82a)
- [Nytt format 1.4.2](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/3d890df7b4d1ca3f199c194b8b84a517d37bf16b)
- [Oppdatert format 1.4.3](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/2e647510f82b3fea2093d365c78e74db7ad14946)
- [Oppdatert format 1.4.4, 1.4.5, 1.4.10, 1.4.11](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/8d99120e8bcd55d3f17b4b2ce204b5fab2334fde)
=> Nytt testregelformat 1.4.1 ->1.4.11

Tests/format.test.ts
Retter en feil i JEST-oppsettet.
=> Oppdatert test

Tests/format.test.ts
=> Lagt til flere tester

Testreglar/3.3.1/Nett/nett-3.3.1b.json
Vi brukte følgende som testcases for denne testregelen:
- Komplett.no Logg inn med Vipps - Skjema med disabled send inn knapp
- fsweb.no Min Profil - Forhåndutfylt skjema
- https://jsfiddle.net/ndXTb/ - Skjema med Client-side live-validation
=> nett-3.3.1b er klar for ks

Testreglar/3.3.1/Nett/nett-3.3.1a.json
Vi brukte følgende som testcases for denne testregelen:
- Komplett.no Logg inn med Vipps - Skjema med disabled send inn knapp
- fsweb.no Min Profil - Forhåndutfylt skjema
- https://jsfiddle.net/ndXTb/ - Skjema med Client-side live-validation
=> nett-3.3.1a er klar for ks

Testreglar/2.4.6/App/app-2.4.6a.json
Det finnes ikke en eksisterende testregel for denne testregelen.
=> app 2.4.6a er klar for ks

Mal/mal.json, Utdatert/1.2.5/Nett/1.2.5a-2022.json, Utdatert/1.3.4/Nett/1.3.4a-2022.json, Utdatert/1.3.5/App/app-android-1.3.5a.json, Utdatert/1.3.5/App/app-ios-1-3-5a.json, Utdatert/1.4.1/Nett/1.4.1a.json, Utdatert/1.4.1/Nett/1.4.1b.json, Utdatert/1.4.1/Nett/1.4.1c.json, Utdatert/1.4.10/Nett/1.4.10a.json, Utdatert/1.4.11/Nett/1.4.11a-2022.json, Utdatert/1.4.4/Nett/1.4.4a.json, Utdatert/2.1.1/2.1.1a.json, Utdatert/2.1.1/app-2.1.1a.json, Utdatert/2.1.2/app/app-2.1.2a.json, Utdatert/2.1.2/nett/2.1.2a.json, Utdatert/2.1.4/Nett/2.1.4a-2022.json, Utdatert/2.4.7/2.4.7a.json, Utdatert/2.5.3/Nett/2.5.3a-2022.json, Utdatert/4.1.2/App/app-4.1.2a-2022.json
- [Fjerna kolonner - utdatert](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/22b1dbf05d1811a53e170a6fafd2fd93c8b1bb3b)
- [Fjerna kolonner fra mal](https://github.com/TilsynForUniversellUtforming/testreglar-wcag-2.x/commit/8171d9722092d8d8768ee56f4b68e8297817b17f)
=> Fjerna kolonner - utdatert

Testreglar/1.3.1/Nett/1.3.1b.json
- Lagt til manglende delutfall for steg 3.9
=> Bug: Lagt til manglende delutfall for steg 3.9

Testreglar/3.2.2/App/app-3.2.2a.json
Det finnes ikke en eksisterende testregel for denne testregelen.
=> app 3.2.2a er klar for ks

Testreglar/2.4.4/App/app-2.4.4a.json
Det finnes ikke en eksisterende testregel for denne testregelen.
=> app 2.4.4a er klar for ks

Doc/Testregelformat/Testregelformat.md
1. Oppdatert dokumentasjon med delutfall
=> Dokumentasjon: Oppdatert dokumentasjon med delutfall

Tests/format.test.ts
- Oppdatert test for format testreglar med ikkje forekomst.
=> test: Oppdatert test av format testreglar

Doc/Testregelformat/Testregelformat.md
Bytta til tabell for testregelformat
=> Oppdatert dokumentasjon

Testreglar/3.1.1/App/app-3.1.1a.json
Det finnes ikke en eksisterende testregel for denne testregelen.
=> app-3.1.1a er klar for ks

Testreglar/3.1.1/Nett/nett-3.1.1a.json, Testreglar/3.1.2/Nett/nett-3.1.2a.json
Retta feil i id - nett-3.1.1a og nett-3.1.2a
=> Retta feil i id - nett-3.1.1a og nett-3.1.2a

.gitignore, Tests/format.test.ts, src/interface/Steg.ts
Endrer StegRadio.svararray til StegRadio.svarArray, som er skrivemåten som brukes i testreglene. Legger til en test som sjekker at steg med type radio har minst to alternativer.
=> verifiserer StegRadio

Tests/format.test.ts, src/interface/Regel.ts
- Rettet fra number til string på RegelTalDersom->verdi
- Lagt til tester for de ulike Regel-typene
=> Retta feil i interface for RegelTalDersom samt oppdatert tester for 

Testreglar/3.3.4/Nett/nett-3.3.4a.json
Vi oppfordrer dere til teste denne testregelen og rutingen grundig. Vi har testet mye, men det er ekstra viktig at dere tester den i ks-runden grundig.
=> nett 3.3.4a er klar for ks

Testreglar/3.3.4/App/app-3.3.4a.json
Vi oppfordrer dere til teste denne testregelen og rutingen grundig. Vi har testet mye, men det er ekstra viktig at dere tester den i ks-runden grundig.
=> app-3.3.4a er klar for ks

Testreglar/3.3.4/Nett/nett-3.3.4b.json
Se ekstra grundig på rutingen.
=> nett-3.3.4b er klar for ks

Testreglar/3.3.4/App/app-3.3.4b.json
Se ekstra grundig på rutingen.
=> app-3.3.4b er klar for ks

Testreglar/2.2.2/Nett/nett-2.2.2a.json
Krav til samsvar har blitt oppdatert etter at det ble oppdaget i gjennomgang av app-2.2.2a #443
=> nett-2.2.2a Krav til samsvar har blitt oppdatert

Testreglar/2.2.1/Nett/nett-2.2.1a.json
Vi har ikke valgt å ta med delutfall med Nei fra andre alternativene enn gjeldene alternativ. Mener dere at vi bør ha delutfall med Nei fra tidligere alternativer i siste utfall? @geirsf @janBeniaminKwiek @ABJORS
=> nett-2.2.1a er klar for ks

Testreglar/2.2.1/App/app-2.2.1a.json
Vi har ikke valgt å ta med delutfall med Nei fra andre alternativene enn gjeldene alternativ. Mener dere at vi bør ha delutfall med Nei fra tidligere alternativer i siste utfall? @geirsf @janBeniaminKwiek @ABJORS
=> app-2.2.1a er klar for ks

Testreglar/1.1.1/Nett/1.1.1d.json, Testreglar/1.1.1/Nett/nett-1.1.1d.json, Testreglar/1.3.1/Nett/nett-1.3.1a.json, Testreglar/1.3.1/Nett/nett-1.3.1b.json, Testreglar/1.3.1/Nett/nett-1.3.1c.json, Testreglar/4.1.2/Nett/nett-4.1.2a.json, Tests/format.test.ts
Oppdatert ruting i testregler listet i sak #504.
Vennligst test grundig.
=> Testlab 2.0 støtte - Rekkefølge på steg i ruting

eslint.config.mjs
estlint: Lagt til mal og utdatert
=> estlint: Lagt til mal og utdatert

.gitignore, index.json, src/indexer.ts
Oppdater index til å ta med utdaterte filer.
=> Oppdatert index

Testreglar/2.4.6/Nett/2.4.6b.json, Testreglar/3.3.3/Nett/3.3.3a.json, Tests/format.test.ts
- Oppdatert tester til å kjenne igjen namn som ender på mellomrom
- Fjernet mellomrom i namnet til 2.4.6b og 3.3.3a
=> fix: Oppdatert test og fjerna mellomrom i testregelnamn

.gitignore, Tests/format.test.ts
test: oppdatert test med sjekk for tomme avsnitt
=> test: oppdatert test med sjekk for tomme avsnitt

Testreglar/1.4.3/Nett/143b2025.json
143bNett2025
Fjernet høykontrastversjon for å følge tolkning
Generelle endringer i HT
=> Nett-1.4.3b Det er tilstrekkeleg kontrast mellom tekst og bakgrunn i bilde av tekst 2025

Testreglar/2.4.6/App/246bApp2025.json
Endret registrering til standardisert format i flere steg. Div småendringer.
=> App-2.4.6b Ledetekstar beskriv skjemaelement 2025

Testreglar/1.3.1/App/app131c2025.json
- Retta språk
- Fjernet tomme mellomrom
=> Mindre feilrettinger app131c2025.json

Testreglar/3.1.1/dok/Doku-3.1.1a Hovudspråket på nettsida er programmatisk bestemt 2025
=> Create Doku-3.1.1a Hovudspråket på nettsida er programmatisk bestemt 2025

Testreglar/1.3.1/dok/Doku-1.3.1a Visuelle overskrifter er korrekt kodet 2025
=> Create Doku-1.3.1a Visuelle overskrifter er korrekt kodet 2025

Testreglar/1.3.1/dok/Doku-1.3.1c Visuelle lister er korrekt kodet 2025
=> Create Doku-1.3.1c Visuelle lister er korrekt kodet 2025

Testreglar/1.1.1/Nett/111a2025.json
=> Nett-1.1.1a Ikke-lenkede bilder har tekstalternativ 2025

Testreglar/1.3.1/Nett/131c2025.json
=> 131c2025 språk
